title: Tony Bytes
description: Personal commentary on life, society, and the times.
url: https://tonybytes.net
baseurl: ""

permalink: /:year/:month/:day/:title/

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  reviews:
    output: true
    permalink: /books/:title/
  bits:
    output: true
    permalink: /bits/:title/

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor
  - scripts
  - docs
  - docker-compose.yml
  - "*.csv"
